# Site settings
title: Un currículum con la experiencia acádemica y laboral de David Peña
description: Un currículum con la experiencia acádemica y laboral de David Peña
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: David Peña
user_description: Muchos de los fracasos se deben a que las personas no fueron conscientes de lo cerca que estaban del éxito cuando se dieron por vencidas.
user_title: Delineante proyectista
email: dpc.pena@protonmail.com
twitter_username: @Dpc75Dpc
github_username:  dpc75
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
